catalog/urls.py
from django.urls import path

from .views import (
    index,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TaskListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TaskDetailView,
    TaskAssigneesUpdateView,
    EmployeeListView,
    EmployeeDetailView,
    EmployeeCreateView,
    EmployeeUpdatePositionView,
    EmployeeDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),
    path(
        "task-types/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),
    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),
    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),
    # Task
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),
    path(
        "tasks/<int:pk>/toggle-assignees-update/",
        TaskAssigneesUpdateView.as_view(),
        name="task-assignees-update"
    ),
    # Employee
    path(
        "employees/",
        EmployeeListView.as_view(),
        name="employee-list"
    ),
    path(
        "employees/<int:pk>/",
        EmployeeDetailView.as_view(),
        name="employee-detail"
    ),
    path(
        "employees/create/",
        EmployeeCreateView.as_view(),
        name="employee-create"
    ),
    path(
        "employees/<int:pk>/update/",
        EmployeeUpdatePositionView.as_view(),
        name="employee-update"
    ),
    path(
        "employee/<int:pk>/delete/",
        EmployeeDeleteView.as_view(),
        name="employee-delete"
    ),
    # Position
    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),
    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),
    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),
    path(
        "position/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    )
]

app_name = "catalog"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class Position(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Employee(AbstractUser):
    position = models.ForeignKey(Position,
                                 related_name="employees",
                                 null=True,
                                 on_delete=models.CASCADE)

    class Meta:
        verbose_name = "employee"
        verbose_name_plural = "employees"

    def __str__(self):
        return (f"{self.username}: "
                f"{self.first_name} {self.last_name} "
                f"({self.position})")

    def get_absolute_url(self):
        return reverse("catalog:employee-detail", kwargs={"pk": self.pk})


class TaskType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("urgent", "🔴 Urgent!!! 🔴"),
        ("high", "🟠 High priority! 🟠"),
        ("medium", "🟡 Medium priority. 🟡"),
        ("low", "🟢 Low priority. 🟢")
    ]

    name = models.CharField(max_length=255)
    description = models.TextField(null=True,
                                   blank=True)
    deadline = models.DateTimeField(null=True,
                                    blank=True)
    is_completer = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=50,
        choices=PRIORITY_CHOICES,
        null=True,
    )
    task_type = models.ForeignKey(TaskType,
                                  related_name="tasks",
                                  on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Employee,
                                       related_name="tasks")

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from catalog.models import TaskType, Employee


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search task type"}
        )
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search task by name"}
        )
    )


class EmployeeSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class EmployeeCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Employee
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "position"
        )


class EmployeePositionUpdateForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ["position"]


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search task type"}
        )
    )

catalog/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpRequest, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from catalog.models import (Task,
                            TaskType,
                            Position,
                            Employee)
from catalog.forms import (TaskTypeSearchForm,
                           TaskSearchForm,
                           EmployeeSearchForm,
                           EmployeeCreationForm,
                           EmployeePositionUpdateForm,
                           PositionSearchForm)


@login_required
def index(request):
    """View function for the home page of the site"""

    num_tasks = Task.objects.count()
    num_types_tasks = TaskType.objects.count()
    num_position = Position.objects.count()
    num_employee = get_user_model().objects.count()

    context = {
        "num_tasks": num_tasks,
        "num_types_tasks": num_types_tasks,
        "num_position": num_position,
        "num_employee": num_employee
    }

    return render(request,
                  "catalog/index.html",
                  context=context)


# Task Type Views
class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    context_object_name = "task_types_list"
    template_name = "catalog/task_types_list"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = TaskType.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    template_name = "catalog/task_type_form.html"
    success_url = reverse_lazy("catalog:task-type-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    template_name = "catalog/task_type_form.html"
    success_url = reverse_lazy("catalog:task-type-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    template_name = "catalog/task_type_confirm_delete.html"
    success_url = reverse_lazy("catalog:task-type-list")


# Task Views
class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        task_type = self.request.GET.get("task_type", "")
        unique_task_types = TaskType.objects.values_list("name",
                                                         flat=True).distinct()
        context["unique_task_types"] = unique_task_types

        context["search_form"] = TaskSearchForm(
            initial={
                "name": name,
                "task_type": task_type
            }
        )

        return context

    def get_queryset(self):
        queryset = Task.objects.all().select_related("task_type")
        name = self.request.GET.get("name")
        task_type = self.request.GET.get("task_type")

        if name:
            queryset = queryset.filter(name__icontains=name)

        if task_type:
            queryset = queryset.filter(task_type=task_type)

        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("catalog:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("catalog:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("catalog:task-list")


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskAssigneesUpdateView(LoginRequiredMixin, generic.View):
    model = Task
    fields = ("assignees",)

    @staticmethod
    def post(request, *args, **kwargs) -> redirect:
        employee = request.user
        task = get_object_or_404(Task, pk=kwargs["pk"])
        queryset = task.assignees.all()
        if employee in queryset:
            task.assignees.remove(employee)
        else:
            task.assignees.add(employee)

        return redirect("catalog:task-detail", pk=kwargs["pk"])


# Employee Views
class EmployeeListView(LoginRequiredMixin, generic.ListView):
    model = Employee
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EmployeeListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = EmployeeSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = super(EmployeeListView, self).get_queryset()
        username = self.request.GET.get("username")

        if username:
            return queryset.filter(username__icontains=username)

        return queryset


class EmployeeCreateView(LoginRequiredMixin, generic.CreateView):
    model = Employee
    form_class = EmployeeCreationForm


class EmployeeDetailView(LoginRequiredMixin, generic.DetailView):
    model = Employee
    queryset = Employee.objects.all().prefetch_related("tasks__task_type")


class EmployeeUpdatePositionView(LoginRequiredMixin, generic.UpdateView):
    model = Employee
    form_class = EmployeePositionUpdateForm
    success_url = reverse_lazy("catalog:employee-list")


class EmployeeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Employee
    success_url = reverse_lazy("catalog:employee-list")


# Position Views
class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 2

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        name = self.request.GET.get("name")

        if name:
            return queryset.filter(name__icontains=name)

        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("catalog:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("catalog:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("catalog:position-list")

templates/catalog/employee_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete employee?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/employee_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ employee.username }}
    <a href="{% url 'catalog:employee-delete' pk=employee.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'catalog:employee-update' pk=employee.id %}" class="btn btn-secondary link-to-page">
      Update position
    </a>
  </h1>

  <p><strong>First name:</strong> {{ employee.first_name }}</p>
  <p><strong>Last name:</strong> {{ employee.last_name }}</p>
  <p><strong>Position:</strong> {{ employee.position }}</p>
  <p><strong>Is staff:</strong> {{ employee.is_staff }}</p>

  <div class="ml-3">
    <h4>Tasks</h4>

    {% for task in employee.tasks.all %}
        <hr>
        <p><strong>Name:</strong> {{ task.name }}</p>
        <p><strong>Type:</strong> {{ task.task_type}}</p>
        <p class="text-muted"><strong>Id:</strong> {{task.id}}</p>

    {% empty %}
      <p>No tasks!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/catalog/employee_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} employee</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/catalog/employee_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>
      Employee List
      <a href="{% url 'catalog:employee-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>
    {% include "includes/search_form.html" %}
    {% if employee_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Position</th>
      </tr>
    {% for employee in employee_list %}
      <tr>
        <td>{{ employee.id }}</td>
        <td>
          <a href="{% url 'catalog:employee-detail' pk=employee.id %}">
            {{ employee.username }}
            {% if user == employee %} (Me){% endif %}
          </a>
        </td>
        <td>{{ employee.first_name }}</td>
        <td>{{ employee.last_name }}</td>
        <td>
          {% if employee.position %}
            {{ employee.position }}
          {% else %}
            <a href="{% url 'catalog:employee-update' pk=employee.id %}">Add position</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}

    </table>
    {% else %}
      <p>There are no employees in the service.</p>
    {% endif %}
{% endblock %}

templates/catalog/index.html
<!--
=========================================================
* Material Kit 2 - v3.0.0
=========================================================

* Product Page:  https://www.creative-tim.com/product/material-kit
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Coded by www.creative-tim.com

 =========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/img/apple-icon.png">

  <title>
    Task Manager
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="presentation-page bg-gray-200">

  {% include 'includes/navigation.html' %}

  <header class="header-2">
    <div class="page-header min-vh-75 relative" style="background-image: url('{{ ASSETS_ROOT }}/img/bg2.jpg')">
      <span class="mask bg-gradient-primary opacity-4"></span>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">Task Manager</h1>
            <p class="lead text-white mt-3">Free and incredibly useful.<br />Boost your productivity.</p>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6">
    <section class="pt-3 pb-4" id="count-stats">
      <div class="container">
        <div class="row">
          <div class="col-lg-9 mx-auto py-3">
            <div class="row">
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"><span id="state1" countTo="{{ num_tasks }}">0</span></h1>
                  <h5 class="mt-3">Tasks</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4 position-relative">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2" countTo="{{ num_employee }}">0</span></h1>
                  <h5 class="mt-3">Employees</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
                <hr class="vertical dark">
              </div>
              <div class="col-md-4">
                <div class="p-3 text-center">
                  <h1 class="text-gradient text-primary"> <span id="state2">{{ num_position }}</span> + {{ num_types_tasks }}</h1>
                  <h5 class="mt-3">Positions and Task Types</h5>
                  <p class="text-sm font-weight-normal">...</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

  <!--   Core JS Files   -->
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <!--  Plugin for TypedJS, full documentation here: https://github.com/inorganik/CountUp.js -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/countup.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/dixonandmoe/rellax -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/rellax.min.js"></script>
  <!--  Plugin for TiltJS, full documentation here: https://gijsroge.github.io/tilt.js/ -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/tilt.min.js"></script>
  <!--  Plugin for Selectpicker - ChoicesJS, full documentation here: https://github.com/jshjohnson/Choices -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/choices.min.js"></script>
  <!--  Plugin for Parallax, full documentation here: https://github.com/wagerfield/parallax  -->
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>
  <!-- Control Center for Material UI Kit: parallax effects, scripts for the example pages etc -->
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/js/material-kit.min.js?v=3.0.0" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>
</body>

</html>

templates/catalog/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete position?</h1>
  <p>All employees of this position will be also deleted.</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/position_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/catalog/position_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Position List
    <a href="{% url 'catalog:position-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% include "includes/search_form.html" %}

  {% if position_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for position in position_list %}
        <tr>
          <td>
              {{ position.id }}
          </td>
          <td>
              {{ position.name }}
          </td>
          <td>
              {{ position.country }}
          </td>
          <td>
              <a href="{% url 'catalog:position-update' pk=position.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'catalog:position-delete' pk=position.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no positions in the service.</p>
  {% endif %}
{% endblock %}

templates/catalog/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    <form action="{% url "catalog:task-assignees-update" pk=task.id %}" method="post">
      {% csrf_token %}
      {% if request.user in task.assignees.all %}
        <input
            type="submit"
            class="btn btn-danger link-to-page"
            value="Delete me from this task" />
      {% else %}
        <input
            type="submit"
            class="btn btn-success link-to-page"
            value="Assign me to this task" />
      {% endif %}
    </form>
  </h1>
  <br>
  <h2>
    Assignees:
  </h2>
  <hr>
  <ul>
    {% for employee in task.assignees.all %}
      <li>{{ employee.username }} ({{ employee.first_name }} {{ employee.last_name }}, {{ employee.position }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/catalog/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/catalog/task_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}

  <h1>
    Task List
    <a href="{% url 'catalog:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  {% include "includes/search_form.html" %}

  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for task in task_list %}
        <tr>
          <td>
              {{ task.id }}
          </td>
          <td>
              <a href="{% url 'catalog:task-detail' pk=task.id%}">{{ task.name }}</a>
          </td>
          <td>
              <a href="{% url 'catalog:task-type-update' pk=task.id %}">
                Update
              </a>
            </td>
            <td>
              <a style="color: red"
                href="{% url 'catalog:task-delete' pk=task.id %}">
                Delete
              </a>
            </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
      <p>There are no tasks in the service.</p>
  {% endif %}
{% endblock %}

templates/catalog/task_type_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task type?</h1>
  <p>All tasks of this type will be also deleted.</p>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/catalog/task_type_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task type</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}